x-variables:
  main-image: &main-image us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/ucdlib-iam-support:v1.14.1
  utils-image: &utils-image us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/ucdlib-iam-support-utils:v1.14.1
services:
  app:
    image: *main-image
    env_file:
      - .env
    environment:
      UCDLIB_BASE_URL: 'https://iam.staff.library.ucdavis.edu'
      APP_REPORT_ERRORS_ENABLED: 'true'
      APP_REPORT_ERRORS_URL: 'https://client-error-reporter-akwemh35fa-uw.a.run.app'
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPORT: 5432
      BACKUP_LOG_TABLE: ${BACKUP_LOG_TABLE:-backup_log}
    ports:
      - ${UCDLIB_APP_HOST_PORT:-3000}:3000
    restart: always
    depends_on:
      - db
    command: node index.js
  cli:
    image: *utils-image
    restart: always
    env_file:
      - .env
    environment:
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPORT: 5432
    depends_on:
      - db
    volumes:
      - ../../utils/db-entrypoint:/app-sql
    command: /cli/cli.sh
  api:
    image: *utils-image
    restart: always
    env_file:
      - .env
    environment:
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPORT: 5432
    ports:
      - ${UCDLIB_API_HOST_PORT:-3002}:3000
    depends_on:
      - db
    command: /api/api.sh
  backup:
    image: *utils-image
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    environment:
      NIGHTLY_BACKUPS: 'true'
      BACKUP_ENV: prod
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GOOGLE_CLOUD_BUCKET: 'itis-iam'
      SQL_FILE_NAME: 'itis-iam.sql.gz'
      BACKUP_LOG_TABLE: ${BACKUP_LOG_TABLE:-backup_log}
    command: /backup/entrypoint.sh
    volumes:
      - ../../secrets/gc-itis-iam-writer-key.json:/etc/service-account.json
  init:
    image: *utils-image
    env_file:
      - .env
    depends_on:
      - db
    environment:
      RUN_INIT: 'true'
      DATA_ENV: prod
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GOOGLE_CLOUD_BUCKET: 'itis-iam'
      SQL_FILE_NAME: 'itis-iam.sql.gz'
    command: /init/init.sh
    volumes:
      - ../../secrets/gc-itis-iam-reader-key.json:/etc/service-account.json
  maintenance:
    image: *utils-image
    restart: always
    env_file:
      - .env
    environment:
      ENABLE_MAINTENANCE: 'true'
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPORT: 5432
    depends_on:
      - db
    command: /maintenance/entrypoint.sh
  db:
    image: postgres:15.3
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
