version: '3'
services:
  app:
    image: {{APP_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    ports:
      - ${UCDLIB_APP_HOST_PORT:-3000}:3000
    restart: always
  cli:
    image: {{UTILS_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    restart: always
    command: /cli/cli.sh