version: '3'
services:
  app:
    image: {{APP_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    ports:
      - ${UCDLIB_APP_HOST_PORT:-3000}:3000
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
    volumes:
      - ../../app/api:/app/api
      - ../../app/client:/app/client
      - ../../app/lib:/app/lib
      - ../../lib:/iam-support-lib
    # command: bash -c "tail -f /dev/null"
  cli:
    image: {{CLI_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
    volumes:
      - ../../cli/bin:/cli/bin
      - ../../cli/lib:/cli/lib
      - ../../lib:/iam-support-lib