version: '3'
services:
  app:
    image: {{APP_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    ports:
      - ${UCDLIB_APP_HOST_PORT:-3000}:3000
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      UCDLIB_RT_QUEUE: ${UCDLIB_RT_QUEUE:-test}
      UCDLIB_RT_USER: ${UCDLIB_RT_USER:-pmanager}
      UCDLIB_RT_FACILITIES_QUEUE: ${UCDLIB_RT_FACILITIES_QUEUE:-test}
      UCDLIB_BASE_URL: ${UCDLIB_BASE_URL:-http://localhost:3000}
      UCDLIB_RT_FORBID_WRITE: ${UCDLIB_RT_FORBID_WRITE:-true}
      KEYCLOAK_ADMIN_BASE_URL: https://sandbox.auth.library.ucdavis.edu
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    volumes:
      - ../../app/api:/app/api
      - ../../app/client:/app/client
      - ../../app/lib:/app/lib
      - ../../lib:/iam-support-lib
    # command: bash -c "tail -f /dev/null"
    command: node index.js
  cli:
    image: {{UTILS_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      UCDLIB_RT_FORBID_WRITE: ${UCDLIB_RT_FORBID_WRITE:-true}
      UCDLIB_RT_QUEUE: ${UCDLIB_RT_QUEUE:-test}
      KEYCLOAK_ADMIN_BASE_URL: https://sandbox.auth.library.ucdavis.edu
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    command: /cli/cli.sh
    volumes:
      - ../../utils/cli/bin:/cli/bin
      - ../../utils/cli/lib:/cli/lib
      - ../utils/db-entrypoint:/cli/sql
      - ../../lib:/iam-support-lib
  api:
    image: {{UTILS_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    ports:
      - ${UCDLIB_API_HOST_PORT:-3001}:3000
    depends_on:
      - db
    environment:
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    command: /api/api.sh
    # command: /api/tail.sh
    volumes:
      - ../../utils/api:/api
      - ../../lib:/iam-support-lib
  backup:
    image: {{UTILS_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      BACKUP_ENV: ${BACKUP_ENV:-localhost}
      KEYCLOAK_ADMIN_BASE_URL: https://sandbox.auth.library.ucdavis.edu
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GOOGLE_CLOUD_BUCKET: 'itis-iam'
      SQL_FILE_NAME: 'itis-iam.sql.gz'
    command: /backup/entrypoint.sh
    volumes:
      - ../../utils/backup:/backup
      - ../../gc-itis-iam-writer-key.json:/etc/service-account.json
  init:
    image: {{UTILS_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      KEYCLOAK_ADMIN_BASE_URL: https://sandbox.auth.library.ucdavis.edu
      RUN_INIT: true
      DATA_ENV: 'prod'
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GOOGLE_CLOUD_BUCKET: 'itis-iam'
      SQL_FILE_NAME: 'itis-iam.sql.gz'
    command: /init/init.sh
    volumes:
      - ../../utils/init:/init
      - ../../gc-itis-iam-reader-key.json:/etc/service-account.json
  maintenance:
    image: {{UTILS_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      KEYCLOAK_ADMIN_BASE_URL: https://sandbox.auth.library.ucdavis.edu
    # command: /maintenance/entrypoint.sh
    command: /maintenance/tail.sh
    volumes:
      - ../../utils/maintenance/src:/maintenance/src
      - ../../utils/maintenance/tail.sh:/maintenance/tail.sh
      - ../../lib:/iam-support-lib
  db:
    image: postgres:{{POSTGRES_TAG}}
    environment:
      POSTGRES_PASSWORD: localhost
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      #- ../../deploy/utils/db-entrypoint:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db-data:
