version: '3'
services:
  app:
    image: {{APP_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    ports:
      - ${UCDLIB_APP_HOST_PORT:-3000}:3000
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      UCDLIB_RT_QUEUE: ${UCDLIB_RT_QUEUE:-test}
      UCDLIB_BASE_URL: ${UCDLIB_BASE_URL:-http://localhost:3000}
      UCDLIB_RT_FORBID_WRITE: ${UCDLIB_RT_FORBID_WRITE:-true}
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    volumes:
      - ../../app/api:/app/api
      - ../../app/client:/app/client
      - ../../app/lib:/app/lib
      - ../../lib:/iam-support-lib
    command: bash -c "tail -f /dev/null"
  cli:
    image: {{UTILS_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    command: /cli/cli.sh
    volumes:
      - ../../utils/cli/bin:/cli/bin
      - ../../utils/cli/lib:/cli/lib
      - ../../lib:/iam-support-lib
  backup:
    image: {{UTILS_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      BACKUP_ENV: ${BACKUP_ENV:-localhost}
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
    command: /backup/entrypoint.sh
    volumes:
      - ../../utils/backup:/backup
      - ../../gc-itis-iam-writer-key.json:/etc/service-account.json
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: localhost
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../deploy/utils/db-entrypoint:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db-data: