version: '3'
services:
  app:
    image: {{APP_IMAGE_NAME}}:{{REPO_TAG}}
    env_file:
      - .env
    ports:
      - ${UCDLIB_APP_HOST_PORT:-3000}:3000
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
    volumes:
      - ../../app:/app
    # command: bash -c "tail -f /dev/null"