x-variables:
  main-image: &main-image localhost/local-dev/ucdlib-iam-support:local-dev
  utils-image: &utils-image localhost/local-dev/ucdlib-iam-support-utils:local-dev
services:
  app:
    image: *main-image
    env_file:
      - .env
    ports:
      - ${UCDLIB_APP_HOST_PORT:-3000}:3000
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      UCDLIB_RT_QUEUE: ${UCDLIB_RT_QUEUE:-test}
      UCDLIB_RT_FACILITIES_QUEUE: ${UCDLIB_RT_FACILITIES_QUEUE:-test}
      UCDLIB_BASE_URL: ${UCDLIB_BASE_URL:-http://localhost:3000}
      UCDLIB_RT_FORBID_WRITE: ${UCDLIB_RT_FORBID_WRITE:-true}
      APP_REPORT_ERRORS_URL: https://client-error-reporter-akwemh35fa-uw.a.run.app
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    volumes:
      - ../../../app:/app
      - /app/node_modules
      - ../../../lib:/iam-support-lib
      - /iam-support-lib/node_modules
    # command: bash -c "tail -f /dev/null"
    command: node index.js
  cli:
    image: *utils-image
    env_file:
      - .env
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      UCDLIB_RT_FORBID_WRITE: ${UCDLIB_RT_FORBID_WRITE:-true}
      UCDLIB_RT_QUEUE: ${UCDLIB_RT_QUEUE:-test}
      UCDLIB_RT_FACILITIES_QUEUE: ${UCDLIB_RT_FACILITIES_QUEUE:-test}
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    command: /cli/cli.sh
    volumes:
      - ../../../utils/cli:/cli
      - /cli/node_modules
      - ../../../lib:/iam-support-lib
      - /iam-support-lib/node_modules
      - ../../utils/db-entrypoint:/app-sql
  api:
    image: *utils-image
    env_file:
      - .env
    ports:
      - ${UCDLIB_API_HOST_PORT:-3002}:3000
    depends_on:
      - db
    environment:
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    command: /api/api.sh
    # command: /api/tail.sh
    volumes:
      - ../../../utils/api:/api
      - /api/node_modules
      - ../../../lib:/iam-support-lib
      - /iam-support-lib/node_modules
  backup:
    image: *utils-image
    env_file:
      - .env
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      BACKUP_ENV: ${BACKUP_ENV:-localhost}
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GOOGLE_CLOUD_BUCKET: 'itis-iam'
      SQL_FILE_NAME: 'itis-iam.sql.gz'
    command: /backup/entrypoint.sh
    volumes:
      - ../../../utils/backup:/backup
      - ../../secrets/gc-itis-iam-writer-key.json:/etc/service-account.json
  init:
    image: *utils-image
    env_file:
      - .env
    depends_on:
      - db
    environment:
      UCDLIB_APP_ENV: ${UCDLIB_APP_ENV:-dev}
      RUN_INIT: true
      DATA_ENV: 'prod'
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GOOGLE_CLOUD_BUCKET: 'itis-iam'
      SQL_FILE_NAME: 'itis-iam.sql.gz'
    command: /init/init.sh
    volumes:
      - ../../../utils/init:/init
      - ../../secrets/gc-itis-iam-reader-key.json:/etc/service-account.json
  maintenance:
    image: *utils-image
    env_file:
      - .env
    depends_on:
      - db
    environment:
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    # command: /maintenance/entrypoint.sh
    command: /maintenance/tail.sh
    volumes:
      - ../../../utils/maintenance:/maintenance
      - /maintenance/node_modules
      - ../../../lib:/iam-support-lib
      - /iam-support-lib/node_modules
  db:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: localhost
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../deploy/utils/db-entrypoint:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db-data:
