version: '3'
services:
  app:
    image: gcr.io/digital-ucdavis-edu/itis-iam-support-app:sandbox
    env_file:
      - .env
    ports:
      - ${UCDLIB_APP_HOST_PORT:-3000}:3000
    restart: always
  cli:
    image: gcr.io/digital-ucdavis-edu/itis-iam-support-utils:sandbox
    env_file:
      - .env
    restart: always
    command: /cli/cli.sh
